#!/usr/bin/env python
# encoding: utf-8

from waflib.Build import BuildContext


APPNAME = 'o2proxy'
VERSION = '0.0.2'

top = '.'
out = 'BUILD'

def options(ctx):
        ctx.load('compiler_cxx')

def configure(ctx):
    print('→ configuring the project in ' + ctx.path.abspath())
    ctx.load('compiler_cxx')

def build(ctx):

    ctx.program(
            target       = APPNAME,
            source       = ['main.cpp', 'utils.cpp', 'server.cpp', 'engine.cpp',
                            'select.cpp', 'poll.cpp', 'poll_async.cpp', 'epoll.cpp',
                            'http.cpp', 'client.cpp', 'proxy_client.cpp',
                            ],
            includes     = ['.',
                            '../../third_party/libproperty/src',
                            '../../third_party/o2logger/src', 
                            ],
            defines     = ['DEBUG=1'],

            # libs
            lib          = ['pthread'],
            #libpath      = ['/usr/lib'],
            
            # static libs
            stlib        = ['property', 'o2logger'],
            stlibpath    = ['../../third_party/libproperty/src/BUILD',
                            '../../third_party/o2logger/src/BUILD',
                            ],
            linkflags    = ['-ggdb3'],
            cxxflags     = ['-ggdb3', '-std=c++11', '-Wall', '-Wpedantic', '-Werror'],
    )
